/**
 * Dev mode entry point — loaded through Vite's module runner.
 * Boots hatk infrastructure and exports the fetch handler.
 */
import { loadConfig } from './config.ts'
import { loadLexicons, storeLexicons, discoverCollections, buildSchemas } from './database/schema.ts'
import { discoverViews } from './views.ts'
import { initDatabase, migrateSchema, getSchemaDump } from './database/db.ts'
import { createAdapter } from './database/adapter-factory.ts'
import { getDialect } from './database/dialect.ts'
import { setSearchPort } from './database/fts.ts'
import { configureRelay, configureCdn, configureOAuth } from './xrpc.ts'
import { initOAuth } from './oauth/server.ts'
import { initServer } from './server-init.ts'
import { createHandler, registerCoreHandlers } from './server.ts'
import { startIndexer } from './indexer.ts'
import { getCursor } from './database/db.ts'
import { runBackfill } from './backfill.ts'
import { rebuildAllIndexes } from './database/fts.ts'
import { relayHttpUrl } from './config.ts'
import { validateLexicons } from '@bigmoves/lexicon'
import { log } from './logger.ts'
import { mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'

process.env.DEV_MODE = '1'

// Boot sequence (mirrors main.ts but exports handler instead of starting server)
const configPath = 'hatk.config.ts'
const configDir = dirname(resolve(configPath))

const config = await loadConfig(configPath)
configureRelay(config.relay)
configureCdn(config.cdn)

const lexicons = loadLexicons(resolve(configDir, 'lexicons'))
const lexiconErrors = validateLexicons([...lexicons.values()])
if (lexiconErrors) {
  for (const [nsid, errors] of Object.entries(lexiconErrors)) {
    for (const err of errors) console.error(`Invalid lexicon ${nsid}: ${err}`)
  }
  throw new Error('Invalid lexicons')
}
storeLexicons(lexicons)

const collections = config.collections.length > 0 ? config.collections : discoverCollections(lexicons)
discoverViews()

const engineDialect = getDialect(config.databaseEngine)
const { schemas, ddlStatements } = buildSchemas(lexicons, collections, engineDialect)

if (config.database !== ':memory:') {
  mkdirSync(dirname(config.database), { recursive: true })
}
const { adapter, searchPort } = await createAdapter(config.databaseEngine)
setSearchPort(searchPort)
await initDatabase(adapter, config.database, schemas, ddlStatements)
await migrateSchema(schemas)

// Write db/schema.sql
try {
  const { mkdirSync, writeFileSync } = await import('node:fs')
  const schemaDir = resolve(configDir, 'db')
  mkdirSync(schemaDir, { recursive: true })
  const schemaDump = await getSchemaDump()
  writeFileSync(
    resolve(schemaDir, 'schema.sql'),
    `-- This file is auto-generated by hatk on startup. Do not edit.\n-- Database engine: ${config.databaseEngine}\n\n${schemaDump}\n`,
  )
  log(`[hatk] Schema written to db/schema.sql`)
} catch {}

// Initialize handlers from server/ directory
await initServer(resolve(configDir, 'server'))

// Register built-in dev.hatk.* handlers so callXrpc() can find them
registerCoreHandlers(collections, config.oauth)
configureOAuth(config.oauth)

if (config.oauth) {
  await initOAuth(config.oauth, config.plc, config.relay)
}

// Start indexer
const collectionSet = new Set(collections)
const cursor = await getCursor('relay')
startIndexer({
  relayUrl: config.relay,
  collections: collectionSet,
  signalCollections: config.backfill.signalCollections ? new Set(config.backfill.signalCollections) : undefined,
  pinnedRepos: config.backfill.repos ? new Set(config.backfill.repos) : undefined,
  cursor,
  fetchTimeout: config.backfill.fetchTimeout,
  maxRetries: config.backfill.maxRetries,
  parallelism: config.backfill.parallelism,
  ftsRebuildInterval: config.ftsRebuildInterval,
})

// Run backfill in background (no restart in dev mode)
runBackfill({
  pdsUrl: relayHttpUrl(config.relay),
  plcUrl: config.plc,
  collections: collectionSet,
  config: config.backfill,
})
  .then(() => rebuildAllIndexes(Array.from(collectionSet)))
  .catch((err) => console.error('[backfill]', err.message))

// Export the handler for Vite middleware
export const handler = createHandler({
  collections: Array.from(collectionSet),
  publicDir: null, // Vite serves static assets in dev
  oauth: config.oauth,
  admins: config.admins,
})

/** Re-scan server/ directory to pick up changed handlers in dev mode. */
export async function reloadServer() {
  await initServer(resolve(configDir, 'server'))
}

export { renderPage } from './renderer.ts'
export { getRenderer } from './renderer.ts'
export { callXrpc } from './xrpc.ts'
export { parseSessionCookie, getSessionCookieName } from './oauth/session.ts'

log(`[hatk] Dev server ready`)
log(`  Relay: ${config.relay}`)
log(`  Database: ${config.database}`)
log(`  Collections: ${collections.join(', ')}`)
